plugins {
    id("com.android.application")
}

android {
    signingConfigs {
        monolithStable {
            storeFile file("monolith-update-key.jks")
            storePassword "JaneUpdate2026"
            keyAlias "janeupdate"
            keyPassword "JaneUpdate2026"
        }
    }
    androidResources {
        noCompress += ["task", "onnx"]
    }

    namespace = "ai.monolith.app"
    compileSdk = 35

    defaultConfig {
        applicationId = "ai.monolith.app"
        minSdk = 24
        targetSdk = 35
        versionCode = 200001
        versionName = "Beta 2.0.01"
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.monolithStable
        }
    }
}


dependencies {
    implementation("com.google.mediapipe:tasks-genai:0.10.27")
    implementation("com.google.mlkit:text-recognition:16.0.1")
    implementation("com.tom-roush:pdfbox-android:2.0.27.0")
    implementation(files("libs/sherpa-onnx-1.13.4.aar"))
}
